version: '3.9'

services:
  app:
    container_name: app
    build: .
    ports:
      - "8000:8000" # app:local-machine
    volumes:
      - .:/usr/src/app
    environment:
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_NAME: booker
      DB_USERNAME: booker-root
      DB_PASSWORD: booker-pass
    depends_on:
      - mysql
  mysql:
    container_name: mysql-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: booker-pass
      MYSQL_DATABASE: booker
      MYSQL_USER: booker-root
      MYSQL_PASSWORD: booker-pass
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
